name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      fail-fast: false

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test

      - name: Crear archivo build simulado
        if: matrix.node-version == '20.x'
        run: echo "Resultado de build para deploy" > build.txt

      - name: Subir artifact
        if: matrix.node-version == '20.x'
        uses: actions/upload-artifact@v3
        with:
          name: resultado-build
          path: build.txt
